// This file is auto-generated by scripts/generateRoutes.js
export interface GeneratedRoute { path: string; component: string }
export const generatedRoutes: GeneratedRoute[] = [
  {
    "path": "/dashboard/behavioral-charter-map",
    "component": "@/pages/BehavioralCharterMap"
  },
  {
    "path": "/dashboard/clinical-fragility-demo",
    "component": "@/pages/ClinicalFragilityDemo"
  },
  {
    "path": "/dashboard/dashboard",
    "component": "@/pages/Dashboard"
  },
  {
    "path": "/dashboard/focus-history",
    "component": "@/pages/FocusHistory"
  },
  {
    "path": "/dashboard/fragility",
    "component": "@/pages/Fragility"
  },
  {
    "path": "/dashboard/good-day",
    "component": "@/pages/GoodDay"
  },
  {
    "path": "/dashboard/habit-consistency",
    "component": "@/pages/HabitConsistency"
  },
  {
    "path": "/dashboard/home",
    "component": "@/pages/Home"
  },
  {
    "path": "/dashboard/intervention-settings",
    "component": "@/pages/InterventionSettings"
  },
  {
    "path": "/dashboard/map-playground",
    "component": "@/pages/MapPlayground"
  },
  {
    "path": "/dashboard/mileage-globe",
    "component": "@/pages/MileageGlobe"
  },
  {
    "path": "/dashboard/not-found",
    "component": "@/pages/NotFound"
  },
  {
    "path": "/dashboard/privacy-dashboard",
    "component": "@/pages/PrivacyDashboard"
  },
  {
    "path": "/dashboard/route-novelty",
    "component": "@/pages/RouteNovelty"
  },
  {
    "path": "/dashboard/route-similarity",
    "component": "@/pages/RouteSimilarity"
  },
  {
    "path": "/dashboard/session-similarity",
    "component": "@/pages/SessionSimilarity"
  },
  {
    "path": "/dashboard/sidebar-demo",
    "component": "@/pages/SidebarDemo"
  },
  {
    "path": "/dashboard/statistics",
    "component": "@/pages/Statistics"
  },
  {
    "path": "/dashboard/timeline-page",
    "component": "@/pages/TimelinePage"
  },
  {
    "path": "/dashboard/visualizations-list",
    "component": "@/pages/VisualizationsList"
  },
  {
    "path": "/dashboard/charts/activity-by-time",
    "component": "@/pages/charts/ActivityByTime"
  },
  {
    "path": "/dashboard/charts/area-chart-interactive",
    "component": "@/pages/charts/AreaChartInteractive"
  },
  {
    "path": "/dashboard/charts/area-chart-load-ratio",
    "component": "@/pages/charts/AreaChartLoadRatio"
  },
  {
    "path": "/dashboard/charts/avg-daily-mileage-radar",
    "component": "@/pages/charts/AvgDailyMileageRadar"
  },
  {
    "path": "/dashboard/charts/bar-chart-default",
    "component": "@/pages/charts/BarChartDefault"
  },
  {
    "path": "/dashboard/charts/bar-chart-horizontal",
    "component": "@/pages/charts/BarChartHorizontal"
  },
  {
    "path": "/dashboard/charts/bar-chart-interactive",
    "component": "@/pages/charts/BarChartInteractive"
  },
  {
    "path": "/dashboard/charts/bar-chart-label-custom",
    "component": "@/pages/charts/BarChartLabelCustom"
  },
  {
    "path": "/dashboard/charts/bar-chart-mixed",
    "component": "@/pages/charts/BarChartMixed"
  },
  {
    "path": "/dashboard/charts/book-network",
    "component": "@/pages/charts/BookNetwork"
  },
  {
    "path": "/dashboard/charts/book-progress-spiral",
    "component": "@/pages/charts/BookProgressSpiral"
  },
  {
    "path": "/dashboard/charts/bookshelf-by-year",
    "component": "@/pages/charts/BookshelfByYear"
  },
  {
    "path": "/dashboard/charts/compact-next-game-card",
    "component": "@/pages/charts/CompactNextGameCard"
  },
  {
    "path": "/dashboard/charts/genre-sankey",
    "component": "@/pages/charts/GenreSankey"
  },
  {
    "path": "/dashboard/charts/genre-sunburst",
    "component": "@/pages/charts/GenreSunburst"
  },
  {
    "path": "/dashboard/charts/ghost-self-rival-chart",
    "component": "@/pages/charts/GhostSelfRivalChart"
  },
  {
    "path": "/dashboard/charts/line-chart-interactive",
    "component": "@/pages/charts/LineChartInteractive"
  },
  {
    "path": "/dashboard/charts/monthly-mileage-pattern",
    "component": "@/pages/charts/MonthlyMileagePattern"
  },
  {
    "path": "/dashboard/charts/peer-benchmark-bands",
    "component": "@/pages/charts/PeerBenchmarkBands"
  },
  {
    "path": "/dashboard/charts/perf-vs-environment-matrix",
    "component": "@/pages/charts/PerfVsEnvironmentMatrix"
  },
  {
    "path": "/dashboard/charts/radar-chart-default",
    "component": "@/pages/charts/RadarChartDefault"
  },
  {
    "path": "/dashboard/charts/radar-chart-workout-by-time",
    "component": "@/pages/charts/RadarChartWorkoutByTime"
  },
  {
    "path": "/dashboard/charts/radial-chart-grid",
    "component": "@/pages/charts/RadialChartGrid"
  },
  {
    "path": "/dashboard/charts/radial-chart-label",
    "component": "@/pages/charts/RadialChartLabel"
  },
  {
    "path": "/dashboard/charts/radial-chart-text",
    "component": "@/pages/charts/RadialChartText"
  },
  {
    "path": "/dashboard/charts/reading-calendar-heatmap",
    "component": "@/pages/charts/ReadingCalendarHeatmap"
  },
  {
    "path": "/dashboard/charts/reading-map",
    "component": "@/pages/charts/ReadingMap"
  },
  {
    "path": "/dashboard/charts/reading-probability-timeline",
    "component": "@/pages/charts/ReadingProbabilityTimeline"
  },
  {
    "path": "/dashboard/charts/reading-speed-violin",
    "component": "@/pages/charts/ReadingSpeedViolin"
  },
  {
    "path": "/dashboard/charts/reading-timeline",
    "component": "@/pages/charts/ReadingTimeline"
  },
  {
    "path": "/dashboard/charts/run-soundtrack-card-demo",
    "component": "@/pages/charts/RunSoundtrackCardDemo"
  },
  {
    "path": "/dashboard/charts/scatter-chart-pace-heart-rate",
    "component": "@/pages/charts/ScatterChartPaceHeartRate"
  },
  {
    "path": "/dashboard/charts/shoe-usage-chart",
    "component": "@/pages/charts/ShoeUsageChart"
  },
  {
    "path": "/dashboard/charts/steps-trend-with-goal",
    "component": "@/pages/charts/StepsTrendWithGoal"
  },
  {
    "path": "/dashboard/charts/time-in-bed-chart",
    "component": "@/pages/charts/TimeInBedChart"
  },
  {
    "path": "/dashboard/charts/training-entropy-heatmap",
    "component": "@/pages/charts/TrainingEntropyHeatmap"
  },
  {
    "path": "/dashboard/charts/treadmill-vs-outdoor",
    "component": "@/pages/charts/TreadmillVsOutdoor"
  },
  {
    "path": "/dashboard/charts/weekly-volume-history-chart",
    "component": "@/pages/charts/WeeklyVolumeHistoryChart"
  },
  {
    "path": "/dashboard/charts/word-tree",
    "component": "@/pages/charts/WordTree"
  }
]
